# Form implementation generated from reading ui file 'PyQt6_Project.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 762)
        MainWindow.setStyleSheet("background-color: rgb(23, 47, 70);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 671, 731))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("#XChatGPT.QWidget{\n"
"    background-color: rgb(108, 117, 125, 65);\n"
"}\n"
" \n"
"\n"
"#输出日志.QWidget{\n"
"    background-color: rgb(108, 117, 125, 65);\n"
"}\n"
"\n"
"#设置.QWidget{\n"
"    background-color: rgb(108, 117, 125, 65);\n"
"}\n"
"\n"
"/*设置TabWidget中QTabBar的样式*/\n"
"QTabBar::tab{\n"
"    background-color: #0B0E11;\n"
"    font-family:Consolas;    /*设置tab中的文本的字体*/\n"
"    font-size:8pt;\n"
"    color:#ced4da;    /*设置tab中的文本的颜色*/\n"
"    border-top-left-radius: 5px;    /*设置tab的边框的圆角（左上圆角）*/\n"
"    border-top-right-radius: 5px;    /*设置tab的边框的圆角（右上圆角）*/\n"
"    min-width: 8px;\n"
"    padding: 5px;\n"
"}\n"
" \n"
"/*设置TabWidget中QTabBar的tab被选中时的样式*/\n"
"QTabBar::tab:selected{\n"
"    background-color: rgb(108, 117, 125, 65);\n"
"}\n"
" \n"
"/*设置TabWidget中鼠标悬浮在QTabBar的tab上，但未选中该Tab的样式*/\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: rgb(0, 35, 46);\n"
"}\n"
" \n"
"/*设置TabWidget的边框的样式*/\n"
"QTabWidget::pane {\n"
"    border: 1px solid rgb(108, 117, 125, 65);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.aiicon = QtWidgets.QLabel(self.tab)
        self.aiicon.setGeometry(QtCore.QRect(10, 340, 71, 71))
        self.aiicon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.aiicon.setAutoFillBackground(False)
        self.aiicon.setStyleSheet("icon:url(./openai.png);\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.aiicon.setText("")
        self.aiicon.setScaledContents(True)
        self.aiicon.setObjectName("aiicon")
        self.userinput = QtWidgets.QTextEdit(self.tab)
        self.userinput.setGeometry(QtCore.QRect(100, 110, 521, 161))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.userinput.setFont(font)
        self.userinput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.userinput.setStyleSheet("background-color: rgb(17, 17, 36);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.userinput.setObjectName("userinput")
        self.usericon = QtWidgets.QLabel(self.tab)
        self.usericon.setGeometry(QtCore.QRect(10, 80, 71, 71))
        self.usericon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.usericon.setAutoFillBackground(False)
        self.usericon.setStyleSheet("icon: url(./usericon.png);\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.usericon.setText("")
        self.usericon.setScaledContents(True)
        self.usericon.setObjectName("usericon")
        self.aiprint = QtWidgets.QTextBrowser(self.tab)
        self.aiprint.setGeometry(QtCore.QRect(100, 380, 521, 281))
        self.aiprint.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.WhatsThisCursor))
        self.aiprint.setStyleSheet("background-color: rgb(17, 17, 36);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.aiprint.setObjectName("aiprint")
        self.entozhcn = QtWidgets.QCheckBox(self.tab)
        self.entozhcn.setGeometry(QtCore.QRect(520, 660, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.entozhcn.setFont(font)
        self.entozhcn.setAcceptDrops(False)
        self.entozhcn.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.entozhcn.setCheckable(True)
        self.entozhcn.setChecked(False)
        self.entozhcn.setAutoRepeat(False)
        self.entozhcn.setAutoExclusive(False)
        self.entozhcn.setObjectName("entozhcn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label.setStyleSheet("color: rgb(244, 244, 244);\n"
"font-family:Consolas;")
        self.label.setObjectName("label")
        self.OK = QtWidgets.QPushButton(self.tab)
        self.OK.setGeometry(QtCore.QRect(510, 280, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.OK.setFont(font)
        self.OK.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.OK.setStyleSheet("background-color: rgb(17, 17, 36);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.OK.setObjectName("OK")
        self.username = QtWidgets.QLabel(self.tab)
        self.username.setGeometry(QtCore.QRect(100, 80, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.username.setObjectName("username")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(100, 340, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.aiicon.raise_()
        self.entozhcn.raise_()
        self.usericon.raise_()
        self.OK.raise_()
        self.username.raise_()
        self.userinput.raise_()
        self.aiprint.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Print = QtWidgets.QTextEdit(self.tab_2)
        self.Print.setGeometry(QtCore.QRect(10, 0, 611, 661))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Print.setFont(font)
        self.Print.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(17, 17, 36);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.Print.setObjectName("Print")
        self.CleanLog = QtWidgets.QPushButton(self.tab_2)
        self.CleanLog.setGeometry(QtCore.QRect(520, 660, 101, 31))
        self.CleanLog.setStyleSheet("color: rgb(245, 245, 245);\n"
"background-color: rgb(17, 17, 36);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.CleanLog.setObjectName("CleanLog")
        self.CleanLog.raise_()
        self.Print.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 611, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.label_3.setObjectName("label_3")
        self.xeshomeURL = QtWidgets.QLineEdit(self.tab_3)
        self.xeshomeURL.setGeometry(QtCore.QRect(20, 30, 600, 31))
        self.xeshomeURL.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(17, 17, 36);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.xeshomeURL.setObjectName("xeshomeURL")
        self.homeURLOK = QtWidgets.QPushButton(self.tab_3)
        self.homeURLOK.setGeometry(QtCore.QRect(530, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.homeURLOK.setFont(font)
        self.homeURLOK.setStyleSheet("background-color: rgb(17, 17, 36);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.homeURLOK.setObjectName("homeURLOK")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.label_4.setObjectName("label_4")
        self.DataInit = QtWidgets.QPushButton(self.tab_3)
        self.DataInit.setGeometry(QtCore.QRect(500, 620, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.DataInit.setFont(font)
        self.DataInit.setStyleSheet("background-color: rgb(17, 17, 36);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.DataInit.setObjectName("DataInit")
        self.tabWidget.addTab(self.tab_3, "")
        self.MoveBox = QtWidgets.QLabel(self.centralwidget)
        self.MoveBox.setGeometry(QtCore.QRect(0, -2, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.MoveBox.setFont(font)
        self.MoveBox.setStyleSheet("background-color: rgb(0, 17, 25);\n"
"color: rgb(255, 255, 255);\n"
"font-family:Consolas;")
        self.MoveBox.setObjectName("MoveBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 7, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(180, 0, 0);\n"
"border-top-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.MoveBox.raise_()
        self.tabWidget.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.aiprint.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Microsoft YaHei UI\';\"><br /></p></body></html>"))
        self.entozhcn.setText(_translate("MainWindow", "中英文转换"))
        self.label.setText(_translate("MainWindow", "目前不支持联系上下文\n"
"输入指令：/get_ChatGPT_Web 获得ChatGPT镜像站\n"
"输入q退出"))
        self.OK.setText(_translate("MainWindow", "确定"))
        self.username.setText(_translate("MainWindow", "您"))
        self.label_2.setText(_translate("MainWindow", "XChatGPT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ChatGPT"))
        self.Print.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Microsoft YaHei UI\';\"><br /></p></body></html>"))
        self.CleanLog.setText(_translate("MainWindow", "清除日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "输出日志"))
        self.label_3.setText(_translate("MainWindow", "登录，请填入学而思主页网址。(自动登录，必须是学而思主页网址，否则无变化)"))
        self.homeURLOK.setText(_translate("MainWindow", "确定"))
        self.label_4.setText(_translate("MainWindow", "更多内容制作中。。。"))
        self.DataInit.setText(_translate("MainWindow", "初始化设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "设置"))
        self.MoveBox.setText(_translate("MainWindow", " ChatXES-1.2.7"))
        self.pushButton.setText(_translate("MainWindow", "╳"))
