# Form implementation generated from reading ui file 'XesUploader.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_XesUploader(object):
    def setupUi(self, XesUploader):
        XesUploader.setObjectName("XesUploader")
        XesUploader.resize(400, 211)
        self.label = QtWidgets.QLabel(XesUploader)
        self.label.setGeometry(QtCore.QRect(140, 0, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.filePath = QtWidgets.QLineEdit(XesUploader)
        self.filePath.setGeometry(QtCore.QRect(20, 50, 291, 31))
        self.filePath.setObjectName("filePath")
        self.label_2 = QtWidgets.QLabel(XesUploader)
        self.label_2.setGeometry(QtCore.QRect(20, 105, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.openFile = QtWidgets.QPushButton(XesUploader)
        self.openFile.setGeometry(QtCore.QRect(314, 50, 71, 31))
        self.openFile.setObjectName("openFile")
        self.upload = QtWidgets.QPushButton(XesUploader)
        self.upload.setGeometry(QtCore.QRect(314, 80, 71, 31))
        self.upload.setObjectName("upload")
        self.finish = QtWidgets.QPushButton(XesUploader)
        self.finish.setGeometry(QtCore.QRect(314, 173, 71, 31))
        self.finish.setObjectName("finish")
        self.fileURL = QtWidgets.QLineEdit(XesUploader)
        self.fileURL.setGeometry(QtCore.QRect(20, 130, 361, 41))
        self.fileURL.setObjectName("fileURL")

        self.retranslateUi(XesUploader)
        self.finish.clicked.connect(XesUploader.close)
        QtCore.QMetaObject.connectSlotsByName(XesUploader)

    def retranslateUi(self, XesUploader):
        _translate = QtCore.QCoreApplication.translate
        XesUploader.setWindowTitle(_translate("XesUploader", "学而思网盘"))
        self.label.setText(_translate("XesUploader", "请输入文件路径"))
        self.label_2.setText(_translate("XesUploader", "文件网址"))
        self.openFile.setText(_translate("XesUploader", "打开"))
        self.upload.setText(_translate("XesUploader", "上传"))
        self.finish.setText(_translate("XesUploader", "完成"))
